[project]
name = "techs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=25.1.0",
    "fastapi>=0.128.0",
    "python-multipart>=0.0.21",
    "uvicorn>=0.40.0",
]
